#!/bin/bash

url=$1
base_dir=$url/recon
declare -a sub_dirs=("scans" "httprobe" "potential_takeovers" "wayback" "wayback/params" "wayback/extensions")

# Function to create directories if not already exists
create_dir() {
    for dir in "${sub_dirs[@]}"; do
        mkdir -p "$base_dir/$dir"
    done
}

# Function to create files if not already exists
create_file() {
    touch "$base_dir/httprobe/alive.txt"
    touch "$base_dir/final.txt"
    touch "$base_dir/potential_takeovers/potential_takeovers.txt"
}

# Call to directory creation function
create_dir

# Call to file creation function
create_file

echo "[+] Harvesting subdomains with assetfinder..."
assetfinder $url | tee "$base_dir/assets.txt"
grep $1 "$base_dir/assets.txt" >> "$base_dir/final.txt"
rm "$base_dir/assets.txt"

echo "[+] Probing for alive domains..."
sort -u "$base_dir/final.txt" | httprobe -s -p https:443 | sed 's/https\?:\/\///' | tr -d ':443' | tee "$base_dir/httprobe/a.txt"
sort -u "$base_dir/httprobe/a.txt" > "$base_dir/httprobe/alive.txt"
rm "$base_dir/httprobe/a.txt"

echo "[+] Checking for possible subdomain takeover..."
subjack -w "$base_dir/final.txt" -t 100 -timeout 30 -ssl -c ~/go/src/github.com/haccer/subjack/fingerprints.json -v 3 -o "$base_dir/potential_takeovers/potential_takeovers.txt"

echo "[+] Scanning for open ports..."
nmap -iL "$base_dir/httprobe/alive.txt" -T4 -oA "$base_dir/scans/scanned.txt"

echo "[+] Scraping wayback data..."
waybackurls < "$base_dir/final.txt" | tee "$base_dir/wayback/wayback_output.txt"
sort -u "$base_dir/wayback/wayback_output.txt"

echo "[+] Pulling and compiling all possible params found in wayback data..."
grep '?*=' "$base_dir/wayback/wayback_output.txt" | cut -d '=' -f 1 | sort -u | tee "$base_dir/wayback/params/wayback_params.txt"
while IFS= read -r line; do echo $line'='; done < "$base_dir/wayback/params/wayback_params.txt"

echo "[+] Pulling and compiling js/php/aspx/jsp/json files from wayback output..."
while IFS= read -r line; do
    ext="${line##*.}"
    case "$ext" in
        "js"|"html"|"json"|"php"|"aspx")
            echo $line | tee -a "$base_dir/wayback/extensions/${ext}1.txt"
            sort -u "$base_dir/wayback/extensions/${ext}1.txt" > "$base_dir/wayback/extensions/${ext}.txt"
            ;;
    esac
done < "$base_dir/wayback/wayback_output.txt"

rm "$base_dir/wayback/extensions/"*1.txt
